services:
  postgres:
    image: postgres:17
    container_name: tobyshorturl-db
    environment:
      POSTGRES_DB: tobyshorturl
      POSTGRES_USER: tobyshorturl
      POSTGRES_PASSWORD: tobyshorturl
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
